name: Debug Fetch and Merge

on:
  workflow_dispatch:

jobs:
  fetch-and-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run fetch and merge script
        run: |
          python fetch_and_merge.py

      - name: Show current directory
        run: pwd

      - name: List all files
        run: ls -alh
