name: Scrape SBIR/STTR Topics

on:
  # Manual trigger
  workflow_dispatch:
  
  # Schedule to run daily at 6 AM UTC (adjust as needed)
  schedule:
    - cron: '0 6 * * *'
  
  # Run on push to main branch (for testing)
  push:
    branches: [ main ]

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright pandas
        playwright install chromium
        playwright install-deps
    
    - name: Run scraper
      run: python sbir_scraper.py
    
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: Commit and push if changed
      run: |
        git add active_sbir_topics*.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update SBIR/STTR topics - $(date +'%Y-%m-%d %H:%M:%S')" && git push)
