name: Fetch and Enrich SBIR Data

on:
  workflow_dispatch:

jobs:
  fetch-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run fetch and merge script
        run: python fetch_and_merge.py

      - name: Commit updated CSV
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add dsip_sbir_enriched.csv
          git commit -m "Update SBIR enriched CSV"
          git push
