name: Update DSIP + SBIR Tracker CSV

on: 
  workflow_dispatch:

permissions:
  contents: write  # ✅ This allows push to the repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Run tracker script
        run: |
          python fetch_and_merge.py

      - name: Commit and push CSV
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dsip_sbir_enriched.csv || echo "Nothing to add"
          git commit -m "Auto-update SBIR dataset from DSIP + SBIR.gov" || echo "Nothing to commit"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git HEAD:main
