name: Update Active SBIR Topics CSV

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *' # Daily at 11 AM Eastern

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python scrape_topics.py

      - name: Commit and push CSVs
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add active_sbir_topics.csv
          git commit -m "Update active SBIR topics CSV"
          git push
